# Generated by Django 3.0.5 on 2020-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200430_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gpa_slider',
            field=models.IntegerField(default=0),
        ),
    ]
